import { ServiceMasterItem } from "../types";

export const DEFAULT_SERVICE_MASTERS: Omit<ServiceMasterItem, "userId">[] = [
  {
    id: "srv_recharge",
    name: "Mobile & DTH Recharge",
    category: "recharge",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Smartphone",
    color: "#3b82f6",
    description: "Prepaid and postpaid mobile/DTH recharges",
    isActive: true,
  },
  {
    id: "srv_aeps",
    name: "AEPS (Aadhaar Enabled Payment)",
    category: "aeps",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Fingerprint",
    color: "#10b981",
    description: "Biometric cash withdrawal, deposit & balance enquiry",
    isActive: true,
  },
  {
    id: "srv_electric_bill",
    name: "Electricity Bill Payment",
    category: "electric_bill",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Zap",
    color: "#f59e0b",
    description: "State electricity board utility payment",
    isActive: true,
  },
  {
    id: "srv_ration_card",
    name: "Ration Card Services",
    category: "ration_card",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Utensils",
    color: "#8b5cf6",
    description: "New application, family member inclusion, print",
    isActive: true,
  },
  {
    id: "srv_voter_card",
    name: "Voter ID Card Services",
    category: "voter_card",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Vote",
    color: "#ec4899",
    description: "Form 6 new voter, Form 8 correction, voter slip/card",
    isActive: true,
  },
  {
    id: "srv_pan_card",
    name: "PAN Card Services",
    category: "pan_card",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "CreditCard",
    color: "#06b6d4",
    description: "New UTI/NSDL PAN card application and correction",
    isActive: true,
  },
  {
    id: "srv_money_transfer",
    name: "Domestic Money Transfer (DMT)",
    category: "money_transfer",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Send",
    color: "#6366f1",
    description: "IMPS/NEFT bank remittance",
    isActive: true,
  },
  {
    id: "srv_aadhaar_services",
    name: "Aadhaar Services & PVC Card",
    category: "aadhaar_services",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "ShieldCheck",
    color: "#14b8a6",
    description: "e-Aadhaar masked download, PVC card order and print",
    isActive: true,
  },
  {
    id: "srv_certificates",
    name: "Government Certificates",
    category: "certificates",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "FileCheck",
    color: "#f97316",
    description: "Caste, Income, Residential, and Domicile certificates",
    isActive: true,
  },
  {
    id: "srv_printing_xerox",
    name: "Printing, Xerox & Lamination",
    category: "printing_xerox",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Printer",
    color: "#64748b",
    description: "B&W / Color document prints, urgent photo, scanning",
    isActive: true,
  },
  {
    id: "srv_ticket_booking",
    name: "IRCTC Train & Bus Ticket Booking",
    category: "ticket_booking",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "TrainTrack",
    color: "#e11d48",
    description: "Railway reservations and state bus tickets",
    isActive: true,
  },
  {
    id: "srv_pm_kisan",
    name: "PM-Kisan Services",
    category: "pm_kisan",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "Wheat",
    color: "#84cc16",
    description: "Biometric e-KYC, beneficiary status and registration",
    isActive: true,
  },
  {
    id: "srv_other",
    name: "Other Digital Seva Task",
    category: "other",
    defaultIncurredCost: 0,
    defaultFee: 0,
    icon: "LayoutGrid",
    color: "#94a3b8",
    description: "Miscellaneous cyber cafe online services",
    isActive: true,
  },
];
